#!/usr/bin/env node
/**
 * Regenerates the BRAND HEX block in app/assets/css/tokens.css from the
 * canonical TS source app/utils/brand-colors.ts. Runs on prebuild via
 * the npm lifecycle (`pretokens` and `prebuild`/`pregenerate`).
 *
 * Two files, one source of truth:
 *  - brand-colors.ts  →  consumed by build-time renderers (takumi OG)
 *  - tokens.css       →  consumed by the browser runtime
 *
 * The TS module stays the canonical one; this script just keeps the
 * CSS in sync.
 */
import { readFile, writeFile } from 'node:fs/promises'

const TS_SOURCE = 'app/utils/brand-colors.ts'
const CSS_TARGET = 'app/assets/css/tokens.css'
const START = '/* BRAND HEX START — generated by scripts/generate-tokens.mjs from\n     app/utils/brand-colors.ts. Edits here will be overwritten on next\n     `npm run gen:tokens` (or prebuild). Edit brand-colors.ts instead. */'
const END = '/* BRAND HEX END */'

// Map camelCase keys in TS to the historical --pxlc-* token names in CSS.
// Kept explicit so casing edge-cases (border-dark-2, on-light, etc.) stay
// pixel-perfect with what the rest of the stylesheet expects.
const NAME_MAP = {
  tealDeep: 'teal-deep',
  tealMid: 'teal-mid',
  cyan: 'cyan',
  coral: 'coral',
  coralDeep: 'coral-deep',
  bgLight: 'bg-light',
  bgDark: 'bg-dark',
  bgDarkSoft: 'bg-dark-soft',
  bgDarkDeep: 'bg-dark-deep',
  ivory: 'ivory',
  ivorySoft: 'ivory-soft',
  textInk: 'text-ink',
  textOnLight: 'text-on-light',
  textSecondary: 'text-secondary',
  textOnDarkSoft: 'text-on-dark-soft',
  border: 'border',
  borderSoft: 'border-soft',
  borderDark: 'border-dark',
  borderDark2: 'border-dark-2',
  white: 'white',
}

const main = async () => {
  const ts = await readFile(TS_SOURCE, 'utf8')

  // Parse `tealDeep: '#036E73',` lines inside the BRAND_HEX const.
  // The grammar is tight (literal hex + single-quoted), so a regex is
  // safer than rolling a TS parser for 20 lines of data.
  const colors = []
  for (const match of ts.matchAll(/(\w+):\s*'(#[0-9A-Fa-f]+)'/g)) {
    const [, key, hex] = match
    const cssName = NAME_MAP[key]
    if (!cssName) {
      console.error(`gen-tokens: unknown brand key "${key}" — add it to NAME_MAP in scripts/generate-tokens.mjs`)
      process.exit(1)
    }
    colors.push(`  --pxlc-${cssName}: ${hex};`)
  }

  if (!colors.length) {
    console.error(`gen-tokens: no BRAND_HEX entries found in ${TS_SOURCE}`)
    process.exit(1)
  }

  // On Windows worktrees `core.autocrlf=true` checks the file out with CRLF,
  // but our START/END constants use `\n`. Normalize before searching, and
  // restore the original EOL when writing back so we don't churn the file.
  const cssRaw = await readFile(CSS_TARGET, 'utf8')
  const hasCRLF = cssRaw.includes('\r\n')
  const css = hasCRLF ? cssRaw.replace(/\r\n/g, '\n') : cssRaw
  const startIdx = css.indexOf(START)
  const endIdx = css.indexOf(END)
  if (startIdx === -1 || endIdx === -1) {
    console.error(`gen-tokens: missing BRAND HEX markers in ${CSS_TARGET}`)
    process.exit(1)
  }

  const before = css.slice(0, startIdx)
  const after = css.slice(endIdx + END.length)
  const block = `${START}\n${colors.join('\n')}\n  ${END}`
  const nextLF = before + block + after
  const next = hasCRLF ? nextLF.replace(/\n/g, '\r\n') : nextLF

  if (next === cssRaw) {
    console.log('gen-tokens: tokens.css already in sync')
    return
  }
  await writeFile(CSS_TARGET, next)
  console.log(`gen-tokens: wrote ${colors.length} colours to tokens.css`)
}

main().catch(err => { console.error(err); process.exit(2) })
